// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rtvauvrqbfqbkibtbgnq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0dmF1dnJxYmZxYmtpYnRiZ25xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzOTgzNzgsImV4cCI6MjA3NDk3NDM3OH0.LuLqXrmbB0zuBLEId5fatLneBKXh2Ivfl1N9ieRFLQo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});